### ISSUE TITLE
Crash when trying to initialize MapKitFactory

### ISSUE THREAD

**Issue by ZherebtsovAlexandr** [yandex/mapkit-android-demo#4]
Crash on this line  `MapKitFactory.initialize(this.getContext());` in Fragment:

```
 @Override
 public void onCreate(Bundle savedInstanceState) {     
        super.onCreate(savedInstanceState);
        MapKitFactory.setApiKey(apiKey);
        MapKitFactory.initialize(this.getContext());
 }
```

Stacktrace:

```
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/ru.app/app_lib/libgnustl_shared.so" is 32-bit instead of 64-bit
                                                                       at java.lang.Runtime.load0(Runtime.java:897)
                                                                       at java.lang.System.load(System.java:1505)
                                                                       at com.yandex.runtime.internal.ReLinker.loadLibrary(ReLinker.java:82)
                                                                       at com.yandex.runtime.Runtime.loadLibrary(Runtime.java:122)
                                                                       at com.yandex.runtime.Runtime.init(Runtime.java:99)
                                                                       at com.yandex.mapkit.MapKitFactory.initialize(MapKitFactory.java:18)
                                                                       at ru.app.ui.fragment.map.MapFragment.onCreate(MapFragment.java:104)
                                                                       at android.support.v4.app.Fragment.performCreate(Fragment.java:2328)
                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1379)
                                                                       at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1188)
                                                                       at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1071)
                                                                       at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:115)
                                                                       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2379)
                                                                       at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2337)
                                                                       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2244)
                                                                       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3255)
                                                                       at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3215)
                                                                       at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:217)
                                                                       at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:509)
                                                                       at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:498)
                                                                       at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:171)
                                                                       at android.app.Activity.performResume(Activity.java:6984)
                                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3470)
                                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3533)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2791)
                                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:163)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6342)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
```

Device: **Xiaomi redmi note 4x**

if you need more information, then let me know.

**Comment by smileman** [comment]
The same issue on **Xiaomi redmi 4 pro**

**Comment by ZherebtsovAlexandr** [comment]
It seems that it falls on any 64-bit devices.

**Comment by IUdalov** [comment]
Now we don't have armv8 binaries.
Meanwhile, armv7 binaries works well on armv8 devices (also they require less disk space).

You can fix it like this.
```
android {
    buildTypes {
        ndk {
            abiFilters("armeabi-v7a", "x86")
        }
    }
}
```

**Comment by PeterStaranchuk** [comment]
this solution doesn't work for me. have an error : Could not find method abiFilters() for arguments [armeabi-v7a, x86] on BuildType_Decorated{name=ndk, debuggable=false, testCoverageEnabled=false, jniDebuggable=false, pseudoLocalesEnabled=false, renderscriptDebuggable=false, renderscriptOptimLevel=3, minifyEnabled=false, zipAlignEnabled=true, signingConfig=null, embedMicroApp=true, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}} of type com.android.build.gradle.internal.dsl.BuildType.
Open File

**Comment by kitttn** [comment]
@PeterStaranchuk 
move `ndk {}` section to `defaultConfig { .. }` instead of `buildTypes { .. }`

**Comment by DEADMC** [comment]
> @PeterStaranchuk
> move `ndk {}` section to `defaultConfig { .. }` instead of `buildTypes { .. }`

it didnt help, still same error
