### ISSUE TITLE
RuntimeException при попытке выполнения SearchManager.submit();

### ISSUE THREAD

**Issue by hmmmk** [yandex/mapkit-android-demo#45]
Stack-trace: 
`java.lang.RuntimeException: Invalid variant value
    Exception stack trace (top 5 entries):
      # 0: 1543064  /data/app/com.izibizy-OJaqo8T0JpkBmD7aqZK4vg==/lib/arm/libcom.yandex.runtime.so _ZN6yandex4maps7runtime9backtrace9BacktraceC1Ev
      # 1: 1552092  /data/app/com.izibizy-OJaqo8T0JpkBmD7aqZK4vg==/lib/arm/libcom.yandex.runtime.so 
      # 2: 1552556  /data/app/com.izibizy-OJaqo8T0JpkBmD7aqZK4vg==/lib/arm/libcom.yandex.runtime.so _ZN6yandex4maps7runtime9ExceptionC2ERKSsNS2_8SeverityE
      # 3: 1928360  /data/app/com.izibizy-OJaqo8T0JpkBmD7aqZK4vg==/lib/arm/libcom.yandex.mapkit.so _ZN6yandex4maps7runtime8bindings7android8internal8ToNativeIN5boost7variantINS0_6mapkit8geometry5PointEISt10shared_ptrINS9_8PolylineEESB_INS9_7PolygonEENS9_11BoundingBoxENS9_6CircleEEEEP8_jobjectvE4fromESK_
      # 4: 4341936  /data/app/com.izibizy-OJaqo8T0JpkBmD7aqZK4vg==/lib/arm/libcom.yandex.mapkit.search.so Java_com_yandex_mapkit_search_internal_SearchManagerBinding_submit__Ljava_lang_String_2Lcom_yandex_mapkit_geometry_Geometry_2Lcom_yandex_mapkit_search_SearchOptions_2Lcom_yandex_mapkit_search_Session_00024SearchListener_2
    
        at com.yandex.mapkit.search.internal.SearchManagerBinding.submit(Native Method)
        at com.izibizy.mvp.fragments.add.address.search.SearchFragment.submitQuery(SearchFragment.kt:40)
        at com.izibizy.mvp.fragments.add.address.search.SearchFragment.access$submitQuery(SearchFragment.kt:20)
        at com.izibizy.mvp.fragments.add.address.search.SearchFragment$searchTextWatcher$1.afterTextChanged(SearchFragment.kt:31)
        at android.widget.TextView.sendAfterTextChanged(TextView.java:10644)
        at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:14069)
        at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1262)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:574)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:504)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:502)
        at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:849)
        at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:199)
        at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:183)
        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:341)
        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

Sources: https://gist.github.com/hmmmk/c4a6836d71b820e89d87c88d723b10bd

**Comment by elricbk** [comment]
Hi!
* It looks like `mapkit.Geometry` is incorrectly initialized
* There is no actual call to `submit` in attached sources. Could you show it?

**Comment by hmmmk** [comment]
> * There is no actual call to `submit` in attached sources. Could you show it?

Wrong link, sorry. I updated the link to source code.

**Comment by elricbk** [comment]
Thanks. You should initialize geometry with one of the [supported types][1]. Default initialization won't do here.

[1]: https://tech.yandex.ru/maps/doc/mapkit/3.x/concepts/android/mapkit-search/ref/com/yandex/mapkit/search/SearchManager-docpage/#method_detail__method_submit___NonNullString___NonNullGeometry___NonNullSearchOptions___NonNullSearchListener

**Comment by hmmmk** [comment]
> Thanks. You should initialize geometry with one of the [supported types](https://tech.yandex.ru/maps/doc/mapkit/3.x/concepts/android/mapkit-search/ref/com/yandex/mapkit/search/SearchManager-docpage/#method_detail__method_submit___NonNullString___NonNullGeometry___NonNullSearchOptions___NonNullSearchListener). Default initialization won't do here.

The error was exactly in this. Now, everything works fine. Thank you!
