### ISSUE TITLE
java.lang.RuntimeException: error in glGetShaderiv: GL_INVALID_OPERATION

### ISSUE THREAD

**Issue by iFr0z** [yandex/mapkit-android-demo#46]
```

> 2018-10-26 00:40:14.663 5830-5869/... E/eglCodecCommon: removeVertexArrayObject: ERROR: cannot delete VAO 0!
> 2018-10-26 00:40:15.394 5830-5869/... E/AndroidRuntime: FATAL EXCEPTION: GLThread 323
>     Process: ..., PID: 5830
>     java.lang.RuntimeException: error in glGetShaderiv: GL_INVALID_OPERATION
>     Exception stack trace (top 20 entries):
>       # 0: 1468776  /data/app/...-RcOAla_D3YKIEhX3fESMpA==/lib/x86/libcom.yandex.runtime.so _ZN6yandex4maps7runtime9backtrace9BacktraceC1Ev
>       # 1: 1478361  /data/app/...-RcOAla_D3YKIEhX3fESMpA==/lib/x86/libcom.yandex.runtime.so 
>       # 2: 1478912  /data/app/...-RcOAla_D3YKIEhX3fESMpA==/lib/x86/libcom.yandex.runtime.so _ZN6yandex4maps7runtime9ExceptionC2ERKSsNS2_8SeverityE
>       # 3: 1397272  /data/app/...-RcOAla_D3YKIEhX3fESMpA==/lib/x86/libcom.yandex.runtime.so _ZN6yandex4maps7runtime12RuntimeErrorC2Ev
>       # 4: 1722013  /data/app/...-RcOAla_D3YKIEhX3fESMpA==/lib/x86/libcom.yandex.runtime.so _ZNK6yandex4maps7runtime8graphics6Shader5valueEj
>       # 5: 1722419  /data/app/...-RcOAla_D3YKIEhX3fESMpA==/lib/x86/libcom.yandex.runtime.so _ZN6yandex4maps7runtime8graphics6ShaderC2ERKSt8functionIFvS4_IFvvEEEEPKcj
>       # 6: 3113766  /data/app/...-RcOAla_D3YKIEhX3fESMpA==/lib/x86/libcom.yandex.mapkit.so 
>       # 7: 3679299  /data/app/...-RcOAla_D3YKIEhX3fESMpA==/lib/x86/libcom.yandex.mapkit.so 
>       # 8: 3680780  /data/app/...-RcOAla_D3YKIEhX3fESMpA==/lib/x86/libcom.yandex.mapkit.so 
>       # 9: 3954192  /data/app/...-RcOAla_D3YKIEhX3fESMpA==/lib/x86/libcom.yandex.mapkit.so 
>       #10: 4058068  /data/app/...-RcOAla_D3YKIEhX3fESMpA==/lib/x86/libcom.yandex.mapkit.so 
>       #11: 4076339  /data/app/...-RcOAla_D3YKIEhX3fESMpA==/lib/x86/libcom.yandex.mapkit.so 
>       #12: 2833466  /data/app/...-RcOAla_D3YKIEhX3fESMpA==/lib/x86/libcom.yandex.runtime.so 
>       #13: 2850323  /data/app/...-RcOAla_D3YKIEhX3fESMpA==/lib/x86/libcom.yandex.runtime.so Java_com_yandex_runtime_view_internal_PlatformViewBinding_onRender
>       #14: 6204312  /system/lib/libart.so 
>       #15: 6179715  /system/lib/libart.so 
>       #16: 618703  /system/lib/libart.so _ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc
>       #17: 2686115  /system/lib/libart.so _ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPNS_11ShadowFrameEtPNS_6JValueE
>       #18: 2658887  /system/lib/libart.so _ZN3art11interpreter6DoCallILb1ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE
>       #19: 5972009  /system/lib/libart.so MterpInvokeVirtualRange
>     
>     error while creating 'N6yandex4maps6mapkit8textures18StaticImageProgramE': error in glGetShaderiv: GL_INVALID_OPERATION
>     Exception stack trace (top 20 entries):
>       # 0: 1468776  /data/app/...-RcOAla_D3YKIEhX3fESMpA==/lib/x86/libcom.yandex.runtime.so _ZN6yandex4maps7runtime9backtrace9BacktraceC1Ev
>       # 1: 1478361  /data/app/...-RcOAla_D3YKIEhX3fESMpA==/lib/x86/libcom.yandex.runtime.so 
>       # 2: 1478912  /data/app/...-RcOAla_D3YKIEhX3fESMpA==/lib/x86/libcom.yandex.runtime.so _ZN6yandex4maps7runtime9ExceptionC2ERKSsNS2_8SeverityE
>       # 3: 1762546  /data/app/...-RcOAla_D3YKIEhX3fESMpA==/lib/x86/libcom.yandex.mapkit.so 
>       # 4: 3679939  /data/app/...-RcOAla_D3YKIEhX3fESMpA==/lib/x86/libcom.yandex.mapkit.so 
>       # 5: 3680780  /data/app/...-RcOAla_D3YKIEhX3fESMpA==/lib/x86/libcom.yandex.mapkit.so 
>       # 6: 3954192  /data/app/...-RcOAla_D3YKIEhX3fESMpA==/lib/x86/libcom.yandex.mapkit.so 
>       # 7: 4058068  /data/app/...-RcOAla_D3YKIEhX3fESMpA==/lib/x86/libcom.yandex.mapkit.so 
>       # 8: 4076339  /data/app/...-RcOAla_D3YKIEhX3fESMpA==/lib/x86/libcom.yandex.mapkit.so 
>       # 9: 2833466  /data/app/...-RcOAla_D3YKIEhX3fESMpA==/lib/x86/libcom.yandex.runtime.so 
> 2018-10-26 00:40:15.395 5830-5869/... E/AndroidRuntime:   #10: 2850323  /data/app/...-RcOAla_D3YKIEhX3fESMpA==/lib/x86/libcom.yandex.runtime.so Java_com_yandex_runtime_view_internal_PlatformViewBinding_onRender
>       #11: 6204312  /system/lib/libart.so 
>       #12: 6179715  /system/lib/libart.so 
>       #13: 618703  /system/lib/libart.so _ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc
>       #14: 2686115  /system/lib/libart.so _ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPNS_11ShadowFrameEtPNS_6JValueE
>       #15: 2658887  /system/lib/libart.so _ZN3art11interpreter6DoCallILb1ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE
>       #16: 5972009  /system/lib/libart.so MterpInvokeVirtualRange
>       #17: 6123554  /system/lib/libart.so ExecuteMterpImpl
>       #18: 2466327  /system/lib/libart.so 
>       #19: 2492317  /system/lib/libart.so _ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadERKNS_20CodeItemDataAccessorEPNS_11ShadowFrameEPNS_6JValueE
>     
>         at com.yandex.runtime.view.internal.PlatformViewBinding.onRender(Native Method)
>         at com.yandex.runtime.view.internal.PlatformGLRenderer.onDrawFrame(PlatformGLRenderer.java:27)
>         at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1571)
>         at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)

```

**Comment by eberkovich** [comment]
Уточните пожалуйста сценарий при котором это воспроизводится.

**Comment by eberkovich** [comment]
А какое устройство?

**Comment by iFr0z** [comment]
@eberkovich эмулятор

**Comment by eberkovich** [comment]
Видимо это ошибка в реализации OpenGL на эмуляторе.
По спецификации, удаление VAO с нулевым индексом - корректная операция.

**Comment by iFr0z** [comment]
@eberkovich Я извиняюсь. Походу зря я шумиху поднял. На реальном устройстве все пучком.

**Comment by eberkovich** [comment]
В любом случае спасибо за информацию, возможно, удастся обойти эту проблему.
