### ISSUE TITLE
Can't set data to VertexBuffer: GL_OUT_OF_MEMORY

### ISSUE THREAD

**Issue by cosic** [yandex/mapkit-android-demo#51]
Крашится при перемещении карты. Без пинов, просто на просмотре карты. 

Xaiomi Mi A1
mapKit: 3.1.2
android: 8.1
compileSdk: 28
buildTools: 28.0.3 
support: 28.0.0

```
Fatal Exception: java.lang.RuntimeException: Can't set data to VertexBuffer: GL_OUT_OF_MEMORY
Exception stack trace (top 10 entries):
  # 0: 1542068  /data/app/packagename.debug-NGx239B8PqQ9q6zNy2xv-Q==/lib/arm/libcom.yandex.runtime.so _ZN6yandex4maps7runtime9backtrace9BacktraceC2Ev
  # 1: 1558292  /data/app/packagename.debug-NGx239B8PqQ9q6zNy2xv-Q==/lib/arm/libcom.yandex.runtime.so 
  # 2: 1558756  /data/app/packagename.debug-NGx239B8PqQ9q6zNy2xv-Q==/lib/arm/libcom.yandex.runtime.so _ZN6yandex4maps7runtime9ExceptionC2ERKSsNS2_8SeverityE
  # 3: 1780372  /data/app/packagename.debug-NGx239B8PqQ9q6zNy2xv-Q==/lib/arm/libcom.yandex.runtime.so 
  # 4: 1790184  /data/app/packagename.debug-NGx239B8PqQ9q6zNy2xv-Q==/lib/arm/libcom.yandex.runtime.so _ZN6yandex4maps7runtime8graphics12VertexBufferC2ERKSt8functionIFvS4_IFvvEEEEPKvNS2_11BufferUsageEjj
  # 5: 4097016  /data/app/packagename.debug-NGx239B8PqQ9q6zNy2xv-Q==/lib/arm/libcom.yandex.mapkit.so 
  # 6: 4227332  /data/app/packagename.debug-NGx239B8PqQ9q6zNy2xv-Q==/lib/arm/libcom.yandex.mapkit.so 
  # 7: 4227856  /data/app/packagename.debug-NGx239B8PqQ9q6zNy2xv-Q==/lib/arm/libcom.yandex.mapkit.so 
  # 8: 2863160  /data/app/packagename.debug-NGx239B8PqQ9q6zNy2xv-Q==/lib/arm/libcom.yandex.runtime.so 
  # 9: 2884616  /data/app/packagename.debug-NGx239B8PqQ9q6zNy2xv-Q==/lib/arm/libcom.yandex.runtime.so Java_com_yandex_runtime_view_internal_PlatformViewBinding_onRender

       at com.yandex.runtime.view.internal.PlatformViewBinding.onRender(PlatformViewBinding.java)
       at com.yandex.runtime.view.internal.PlatformGLRenderer.onDrawFrame(PlatformGLRenderer.java:27)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1609)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1293)
```

**Comment by eberkovich** [comment]
Причиной out of memory может быть отсутствие вызова MapView.onMemoryWarning.
 **
     * Should be called from ComponentCallbacks2.onTrimMemory.
     * Recommended levels are TRIM_MEMORY_RUNNING_LOW (foreground) and TRIM_MEMORY_COMPLETE(background).
     */
    public void onMemoryWarning() {

**Comment by cosic** [comment]
@eberkovich Кажется помогло. 

У вас не получится спрятать этот вызов по капот? По сути, уже есть внешнее API с пробрасыванием onStart/onStop. Можно подвязаться к жизненному циклу экрана через ActivityLifecycleCallbacks или, если это не имеет особого значения, подвязаться на Application как-нибудь так:
```
private val componentCallbacksListener = object : ComponentCallbacks2 {
    override fun onTrimMemory(level: Int) = onMemoryWarning()

    override fun onConfigurationChanged(newConfig: Configuration) { }

    override fun onLowMemory() = onMemoryWarning()
}

override fun onStart() = applicationContext.registerComponentCallbacks(componentCallbacksListener)

override fun onStop() = applicationContext.unregisterComponentCallbacks(componentCallbacksListener)
```

**Comment by eberkovich** [comment]
Спасибо, да у нас запланировано попробовать спрятать этот вызов.
