### ISSUE TITLE
SearchFactory, UnsatisfiedLinkError: Native method not found

### ISSUE THREAD

**Issue by zuyevpro** [yandex/mapkit-android-demo#55]
```
private double latitude, longitude;
private void yandexGeocoder() {
	SearchManager sm = SearchFactory.getInstance().createSearchManager(SearchManagerType.ONLINE);
	SearchOptions so = new SearchOptions();
	so.setGeometry(true);
	so.setSearchTypes(1); // GEO

	sm.submit(new Point(latitude, longitude), 16, so, this);
}
```

Это даёт Exception:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.app, PID: 7112
    java.lang.UnsatisfiedLinkError: Native method not found: com.yandex.mapkit.search.SearchFactory.getInstance:()Lcom/yandex/mapkit/search/Search;
        at com.yandex.mapkit.search.SearchFactory.getInstance(Native Method)
        at com.example.app.ui.fragment.MyFragment.yandexGeocoder(MyFragment.java:648)
        at com.example.app.ui.fragment.MyFragment.handleCoordinatesChange(MyFragment.java:612)
        at com.example.app.ui.fragment.MyFragment.setNewLocation(MyFragment.java:680)
        at com.example.app.ui.fragment.MyFragment.setCustomLocation(MyFragment.java:686)
        at com.example.app.ui.activity.MyActivity.onActivityResult(MyActivity.java:82)
        at android.app.Activity.dispatchActivityResult(Activity.java:5456)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:3549)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3596)
        at android.app.ActivityThread.access$1300(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:5292)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
        at dalvik.system.NativeStart.main(Native Method)

Android 4.4.2
Версия mapkit и модуля search: 3.2.0 (на 3.1.2 было тоже самое)

**Comment by IUdalov** [comment]
Кажется вы забываете вызвать `SearchFactory.initialize(context);`.
