### ISSUE TITLE
Креш при вызове метода PlatformViewBinding.onRender: Can't set data to IndexBuffer: GL_INVALID_OPERATION

### ISSUE THREAD

**Issue by ZherebtsovAlexandr** [yandex/mapkit-android-demo#62]
Проблема относится не к демо приложению, а к MapKit в целом.

### Версия MapKit
3.2.0

### Устройства
Проявляется на приличном количестве Samsung GT-I9505 c Android 6.0.
И один раз на Philips Xenium V787 с Android 5.0.
Я думаю причина не в устройстве, а в том, что с таким Samsung много пользователей, возможно это повлияло на статистику.

### Проблема
Аналитика показывает такой вот креш, к сожалению, отследить сценарии или воспроизвести не удалось:

```
Fatal Exception: java.lang.RuntimeException: Can't set data to IndexBuffer: GL_INVALID_OPERATION
Exception stack trace (top 14 entries):
  # 0: 1542068  libcom.yandex.runtime.so _ZN6yandex4maps7runtime9backtrace9BacktraceC2Ev
  # 1: 1558292  libcom.yandex.runtime.so 
  # 2: 1558756  libcom.yandex.runtime.so _ZN6yandex4maps7runtime9ExceptionC2ERKSsNS2_8SeverityE
  # 3: 1780372  libcom.yandex.runtime.so 
  # 4: 1794004  libcom.yandex.runtime.so _ZN6yandex4maps7runtime8graphics11IndexBufferC2ERKSt8functionIFvS4_IFvvEEEEPKtNS2_11BufferUsageEj
  # 5: 3281940  libcom.yandex.mapkit.so 
  # 6: 3282272  libcom.yandex.mapkit.so 
  # 7: 4076080  libcom.yandex.mapkit.so 
  # 8: 3977904  libcom.yandex.mapkit.so 
  # 9: 4350912  libcom.yandex.mapkit.so 
  #10: 4195272  libcom.yandex.mapkit.so 
  #11: 4227856  libcom.yandex.mapkit.so 
  #12: 2863160  libcom.yandex.runtime.so 
  #13: 2884616  libcom.yandex.runtime.so Java_com_yandex_runtime_view_internal_PlatformViewBinding_onRender

       at com.yandex.runtime.view.internal.PlatformViewBinding.onRender(PlatformViewBinding.java)
       at com.yandex.runtime.view.internal.PlatformGLRenderer.onDrawFrame(PlatformGLRenderer.java:27)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1531)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)
```

**Comment by eberkovich** [comment]
Знаем про эту проблему,  исправление уже есть, войдет в ближайший релиз.

**Comment by eberkovich** [comment]
Исправлено в версии 3.3.1.
