### ISSUE TITLE
Fatal Exception при загрузке на Samsung S10 (SM-G973F)

### ISSUE THREAD

**Issue by cdump** [yandex/mapkit-android-demo#74]
Начали прилетать странные крэши от юзеров Galaxy S10, пока ни одного успешного запуска на этом телефоне:

mapkit 3.3.1
Model: SM-G973F
Os Version: 9

```
Fatal Exception: java.lang.UnsatisfiedLinkError: Couldn't load c++_shared
       at com.yandex.runtime.Runtime.loadLibrary(Runtime.java:124)
       at com.yandex.runtime.Runtime.init(Runtime.java:99)
       at com.yandex.mapkit.MapKitFactory.initialize(MapKitFactory.java:20)
       at myapp.MainActivity.onCreate(MainActivity.kt:115)
       at android.app.Activity.performCreate(Activity.java:7327)
       at android.app.Activity.performCreate(Activity.java:7318)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3087)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3250)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1947)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7032)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

**Comment by vitalyleon** [comment]
MapKit 3.3.1
Аналогичные краши на:
1) Samsung Galaxy J7 (SM-J730FM), OS: 8.1.0
2) Fly Cirrus 11 (FS517), OS: 6.0
